### ISSUE TITLE
关于基于MobileNet V3 的改造

### ISSUE THREAD

**Issue by chenyyx** [TMaysGGS/MobileFaceNet-Keras#1]
你好，我查看了您的 MobileFaceNet 的 keras 实现，感觉真的很棒，非常感谢您做的这么 nice 的工作。现在，我有个问题，希望向您请教一下。基于 mobilefacenet 的形式，我使用 keras 实现了 mobilenet v3，并且希望也将 mobilenet v3 改成 mobilefacenet 这样的网络（主要参考您的代码）用于 人脸识别 等工作。但是实际改下来，查看结果并不是很理想，loss 下降缓慢，acc 也很难提升。楼主关于我这个情况，您有什么见解吗？期待得到您的回复，谢谢。

**Comment by TMaysGGS** [comment]
> 你好，我查看了您的 MobileFaceNet 的 keras 实现，感觉真的很棒，非常感谢您做的这么 nice 的工作。现在，我有个问题，希望向您请教一下。基于 mobilefacenet 的形式，我使用 keras 实现了 mobilenet v3，并且希望也将 mobilenet v3 改成 mobilefacenet 这样的网络（主要参考您的代码）用于 人脸识别 等工作。但是实际改下来，查看结果并不是很理想，loss 下降缓慢，acc 也很难提升。楼主关于我这个情况，您有什么见解吗？期待得到您的回复，谢谢。

你好，我最近工作较忙，没有尝试去复现MobileNetV3。但听一个朋友的说法，他在尝试时遇到了和你类似的问题，当时我们硬件受限所以没有继续训练下去。我想一方面一些基本的调试（选用Adam代替SGD，用较大的学习率做初始学习率等）你或许已经尝试过了，另一方面我想可以先拿一个小数据集（如1000个人每人100张图片）试一下你搭建的网络，如果在小数据集上loss下降并且分类精度足够高的话那至少证明你的网络搭建是对的。
另外关于MobileNetV3我自己的理解是：它是通过模型选择技术挑出最优方案的，也就是说是为了当时的分类任务特化，是不是有可能在做人脸分类这个任务上各项超参数应该重新选择呢？我这边依旧因为硬件条件受限和工作有些紧张暂时无法尝试，或许你可以用你搭建的Keras版模型做论文中原来的分类任务：成功的话不但证明你的模型无误，还能迁移学习到你的人脸分类训练上。
我学深度学习时间只有一年半，也经常遇到各种问题，可能说得不是很对，希望以后有机会能多讨论。

**Comment by chenyyx** [comment]
> > 你好，我查看了您的 MobileFaceNet 的 keras 实现，感觉真的很棒，非常感谢您做的这么 nice 的工作。现在，我有个问题，希望向您请教一下。基于 mobilefacenet 的形式，我使用 keras 实现了 mobilenet v3，并且希望也将 mobilenet v3 改成 mobilefacenet 这样的网络（主要参考您的代码）用于 人脸识别 等工作。但是实际改下来，查看结果并不是很理想，loss 下降缓慢，acc 也很难提升。楼主关于我这个情况，您有什么见解吗？期待得到您的回复，谢谢。
> 
> 你好，我最近工作较忙，没有尝试去复现MobileNetV3。但听一个朋友的说法，他在尝试时遇到了和你类似的问题，当时我们硬件受限所以没有继续训练下去。我想一方面一些基本的调试（选用Adam代替SGD，用较大的学习率做初始学习率等）你或许已经尝试过了，另一方面我想可以先拿一个小数据集（如1000个人每人100张图片）试一下你搭建的网络，如果在小数据集上loss下降并且分类精度足够高的话那至少证明你的网络搭建是对的。
> 另外关于MobileNetV3我自己的理解是：它是通过模型选择技术挑出最优方案的，也就是说是为了当时的分类任务特化，是不是有可能在做人脸分类这个任务上各项超参数应该重新选择呢？我这边依旧因为硬件条件受限和工作有些紧张暂时无法尝试，或许你可以用你搭建的Keras版模型做论文中原来的分类任务：成功的话不但证明你的模型无误，还能迁移学习到你的人脸分类训练上。
> 我学深度学习时间只有一年半，也经常遇到各种问题，可能说得不是很对，希望以后有机会能多讨论。

谢谢！这么快得到您的解答，实在是太感谢了。我现在能确定的，是 MobileNet V3 网络没问题，但是，我在网络后面添加用于人脸分类任务的网络结构时（如您代码中的 class ArcFaceLossLayer(Layer)），在训练时， loss 无法下降，甚至有时候还会上升:(，acc 也很低。基本上可以宣告我在后边添加的这部分是爆炸的了。
如你刚才所提到的，优化函数和学习率等这些，我都已经尝试过，但是效果依旧很差。想跟你请教下，在后面添加 class ArcFaceLossLayer(Layer) 这部分代码时，是否有什么需要注意的呢？或者说有什么小细节我没有注意到？（比如，Dropout，Flatten，Dense 等等）这两天修改了很多版本了，依然无能为力。再次感谢。

**Comment by TMaysGGS** [comment]
> > > 你好，我查看了您的 MobileFaceNet 的 keras 实现，感觉真的很棒，非常感谢您做的这么 nice 的工作。现在，我有个问题，希望向您请教一下。基于 mobilefacenet 的形式，我使用 keras 实现了 mobilenet v3，并且希望也将 mobilenet v3 改成 mobilefacenet 这样的网络（主要参考您的代码）用于 人脸识别 等工作。但是实际改下来，查看结果并不是很理想，loss 下降缓慢，acc 也很难提升。楼主关于我这个情况，您有什么见解吗？期待得到您的回复，谢谢。
> > 
> > 
> > 你好，我最近工作较忙，没有尝试去复现MobileNetV3。但听一个朋友的说法，他在尝试时遇到了和你类似的问题，当时我们硬件受限所以没有继续训练下去。我想一方面一些基本的调试（选用Adam代替SGD，用较大的学习率做初始学习率等）你或许已经尝试过了，另一方面我想可以先拿一个小数据集（如1000个人每人100张图片）试一下你搭建的网络，如果在小数据集上loss下降并且分类精度足够高的话那至少证明你的网络搭建是对的。
> > 另外关于MobileNetV3我自己的理解是：它是通过模型选择技术挑出最优方案的，也就是说是为了当时的分类任务特化，是不是有可能在做人脸分类这个任务上各项超参数应该重新选择呢？我这边依旧因为硬件条件受限和工作有些紧张暂时无法尝试，或许你可以用你搭建的Keras版模型做论文中原来的分类任务：成功的话不但证明你的模型无误，还能迁移学习到你的人脸分类训练上。
> > 我学深度学习时间只有一年半，也经常遇到各种问题，可能说得不是很对，希望以后有机会能多讨论。
> 
> 谢谢！这么快得到您的解答，实在是太感谢了。我现在能确定的，是 MobileNet V3 网络没问题，但是，我在网络后面添加用于人脸分类任务的网络结构时（如您代码中的 class ArcFaceLossLayer(Layer)），在训练时， loss 无法下降，甚至有时候还会上升:(，acc 也很低。基本上可以宣告我在后边添加的这部分是爆炸的了。
> 如你刚才所提到的，优化函数和学习率等这些，我都已经尝试过，但是效果依旧很差。想跟你请教下，在后面添加 class ArcFaceLossLayer(Layer) 这部分代码时，是否有什么需要注意的呢？或者说有什么小细节我没有注意到？（比如，Dropout，Flatten，Dense 等等）这两天修改了很多版本了，依然无能为力。再次感谢。

这个自定义的loss层已经封装好了，你只要确认输入输出是对的就行，小细节上的超参数设定只会让训练的最终精度有所偏差，一般不会在一开始的时候就不收敛。你已经确认了模型结构没问题的话，如果学习率你已经尝试过不同的几个数量级都没有用，那是不是有可能是你的数据和对应标签有些问题？ArcFaceLoss只是用来给人脸识别项目锦上添花的，你可以试试不接这个层直接用Softmax输出的交叉熵作为损失函数训练几个Epoch试试，如果收敛那就是loss问题，如果没有那很可能是数据处理的时候出了一些问题。另外还有Margin Loss、Cosine Loss你也可以试试，接上不同的loss层对比效果等。不过以上都是我个人见解哈。

**Comment by chenyyx** [comment]
> > > > 你好，我查看了您的 MobileFaceNet 的 keras 实现，感觉真的很棒，非常感谢您做的这么 nice 的工作。现在，我有个问题，希望向您请教一下。基于 mobilefacenet 的形式，我使用 keras 实现了 mobilenet v3，并且希望也将 mobilenet v3 改成 mobilefacenet 这样的网络（主要参考您的代码）用于 人脸识别 等工作。但是实际改下来，查看结果并不是很理想，loss 下降缓慢，acc 也很难提升。楼主关于我这个情况，您有什么见解吗？期待得到您的回复，谢谢。
> > > 
> > > 
> > > 你好，我最近工作较忙，没有尝试去复现MobileNetV3。但听一个朋友的说法，他在尝试时遇到了和你类似的问题，当时我们硬件受限所以没有继续训练下去。我想一方面一些基本的调试（选用Adam代替SGD，用较大的学习率做初始学习率等）你或许已经尝试过了，另一方面我想可以先拿一个小数据集（如1000个人每人100张图片）试一下你搭建的网络，如果在小数据集上loss下降并且分类精度足够高的话那至少证明你的网络搭建是对的。
> > > 另外关于MobileNetV3我自己的理解是：它是通过模型选择技术挑出最优方案的，也就是说是为了当时的分类任务特化，是不是有可能在做人脸分类这个任务上各项超参数应该重新选择呢？我这边依旧因为硬件条件受限和工作有些紧张暂时无法尝试，或许你可以用你搭建的Keras版模型做论文中原来的分类任务：成功的话不但证明你的模型无误，还能迁移学习到你的人脸分类训练上。
> > > 我学深度学习时间只有一年半，也经常遇到各种问题，可能说得不是很对，希望以后有机会能多讨论。
> > 
> > 
> > 谢谢！这么快得到您的解答，实在是太感谢了。我现在能确定的，是 MobileNet V3 网络没问题，但是，我在网络后面添加用于人脸分类任务的网络结构时（如您代码中的 class ArcFaceLossLayer(Layer)），在训练时， loss 无法下降，甚至有时候还会上升:(，acc 也很低。基本上可以宣告我在后边添加的这部分是爆炸的了。
> > 如你刚才所提到的，优化函数和学习率等这些，我都已经尝试过，但是效果依旧很差。想跟你请教下，在后面添加 class ArcFaceLossLayer(Layer) 这部分代码时，是否有什么需要注意的呢？或者说有什么小细节我没有注意到？（比如，Dropout，Flatten，Dense 等等）这两天修改了很多版本了，依然无能为力。再次感谢。
> 
> 这个自定义的loss层已经封装好了，你只要确认输入输出是对的就行，小细节上的超参数设定只会让训练的最终精度有所偏差，一般不会在一开始的时候就不收敛。你已经确认了模型结构没问题的话，如果学习率你已经尝试过不同的几个数量级都没有用，那是不是有可能是你的数据和对应标签有些问题？ArcFaceLoss只是用来给人脸识别项目锦上添花的，你可以试试不接这个层直接用Softmax输出的交叉熵作为损失函数训练几个Epoch试试，如果收敛那就是loss问题，如果没有那很可能是数据处理的时候出了一些问题。另外还有Margin Loss、Cosine Loss你也可以试试，接上不同的loss层对比效果等。不过以上都是我个人见解哈。

好的，了解啦 ^_^，这么忙还打扰您，有些抱歉。非常非常感谢。

**Comment by TMaysGGS** [comment]
> > > > > 你好，我查看了您的 MobileFaceNet 的 keras 实现，感觉真的很棒，非常感谢您做的这么 nice 的工作。现在，我有个问题，希望向您请教一下。基于 mobilefacenet 的形式，我使用 keras 实现了 mobilenet v3，并且希望也将 mobilenet v3 改成 mobilefacenet 这样的网络（主要参考您的代码）用于 人脸识别 等工作。但是实际改下来，查看结果并不是很理想，loss 下降缓慢，acc 也很难提升。楼主关于我这个情况，您有什么见解吗？期待得到您的回复，谢谢。
> > > > 
> > > > 
> > > > 你好，我最近工作较忙，没有尝试去复现MobileNetV3。但听一个朋友的说法，他在尝试时遇到了和你类似的问题，当时我们硬件受限所以没有继续训练下去。我想一方面一些基本的调试（选用Adam代替SGD，用较大的学习率做初始学习率等）你或许已经尝试过了，另一方面我想可以先拿一个小数据集（如1000个人每人100张图片）试一下你搭建的网络，如果在小数据集上loss下降并且分类精度足够高的话那至少证明你的网络搭建是对的。
> > > > 另外关于MobileNetV3我自己的理解是：它是通过模型选择技术挑出最优方案的，也就是说是为了当时的分类任务特化，是不是有可能在做人脸分类这个任务上各项超参数应该重新选择呢？我这边依旧因为硬件条件受限和工作有些紧张暂时无法尝试，或许你可以用你搭建的Keras版模型做论文中原来的分类任务：成功的话不但证明你的模型无误，还能迁移学习到你的人脸分类训练上。
> > > > 我学深度学习时间只有一年半，也经常遇到各种问题，可能说得不是很对，希望以后有机会能多讨论。
> > > 
> > > 
> > > 谢谢！这么快得到您的解答，实在是太感谢了。我现在能确定的，是 MobileNet V3 网络没问题，但是，我在网络后面添加用于人脸分类任务的网络结构时（如您代码中的 class ArcFaceLossLayer(Layer)），在训练时， loss 无法下降，甚至有时候还会上升:(，acc 也很低。基本上可以宣告我在后边添加的这部分是爆炸的了。
> > > 如你刚才所提到的，优化函数和学习率等这些，我都已经尝试过，但是效果依旧很差。想跟你请教下，在后面添加 class ArcFaceLossLayer(Layer) 这部分代码时，是否有什么需要注意的呢？或者说有什么小细节我没有注意到？（比如，Dropout，Flatten，Dense 等等）这两天修改了很多版本了，依然无能为力。再次感谢。
> > 
> > 
> > 这个自定义的loss层已经封装好了，你只要确认输入输出是对的就行，小细节上的超参数设定只会让训练的最终精度有所偏差，一般不会在一开始的时候就不收敛。你已经确认了模型结构没问题的话，如果学习率你已经尝试过不同的几个数量级都没有用，那是不是有可能是你的数据和对应标签有些问题？ArcFaceLoss只是用来给人脸识别项目锦上添花的，你可以试试不接这个层直接用Softmax输出的交叉熵作为损失函数训练几个Epoch试试，如果收敛那就是loss问题，如果没有那很可能是数据处理的时候出了一些问题。另外还有Margin Loss、Cosine Loss你也可以试试，接上不同的loss层对比效果等。不过以上都是我个人见解哈。
> 
> 好的，了解啦 ^_^，这么忙还打扰您，有些抱歉。非常非常感谢。

嗯别客气 :)

**Comment by LeonFaith** [comment]
膜拜大神，编程之光。

**Comment by TMaysGGS** [comment]
> 膜拜大神，编程之光。

壕哥饶命啊……你这黑得我直接要gg啊……

**Comment by TMaysGGS** [comment]
> > > > > 你好，我查看了您的 MobileFaceNet 的 keras 实现，感觉真的很棒，非常感谢您做的这么 nice 的工作。现在，我有个问题，希望向您请教一下。基于 mobilefacenet 的形式，我使用 keras 实现了 mobilenet v3，并且希望也将 mobilenet v3 改成 mobilefacenet 这样的网络（主要参考您的代码）用于 人脸识别 等工作。但是实际改下来，查看结果并不是很理想，loss 下降缓慢，acc 也很难提升。楼主关于我这个情况，您有什么见解吗？期待得到您的回复，谢谢。
> > > > 
> > > > 
> > > > 你好，我最近工作较忙，没有尝试去复现MobileNetV3。但听一个朋友的说法，他在尝试时遇到了和你类似的问题，当时我们硬件受限所以没有继续训练下去。我想一方面一些基本的调试（选用Adam代替SGD，用较大的学习率做初始学习率等）你或许已经尝试过了，另一方面我想可以先拿一个小数据集（如1000个人每人100张图片）试一下你搭建的网络，如果在小数据集上loss下降并且分类精度足够高的话那至少证明你的网络搭建是对的。
> > > > 另外关于MobileNetV3我自己的理解是：它是通过模型选择技术挑出最优方案的，也就是说是为了当时的分类任务特化，是不是有可能在做人脸分类这个任务上各项超参数应该重新选择呢？我这边依旧因为硬件条件受限和工作有些紧张暂时无法尝试，或许你可以用你搭建的Keras版模型做论文中原来的分类任务：成功的话不但证明你的模型无误，还能迁移学习到你的人脸分类训练上。
> > > > 我学深度学习时间只有一年半，也经常遇到各种问题，可能说得不是很对，希望以后有机会能多讨论。
> > > 
> > > 
> > > 谢谢！这么快得到您的解答，实在是太感谢了。我现在能确定的，是 MobileNet V3 网络没问题，但是，我在网络后面添加用于人脸分类任务的网络结构时（如您代码中的 class ArcFaceLossLayer(Layer)），在训练时， loss 无法下降，甚至有时候还会上升:(，acc 也很低。基本上可以宣告我在后边添加的这部分是爆炸的了。
> > > 如你刚才所提到的，优化函数和学习率等这些，我都已经尝试过，但是效果依旧很差。想跟你请教下，在后面添加 class ArcFaceLossLayer(Layer) 这部分代码时，是否有什么需要注意的呢？或者说有什么小细节我没有注意到？（比如，Dropout，Flatten，Dense 等等）这两天修改了很多版本了，依然无能为力。再次感谢。
> > 
> > 
> > 这个自定义的loss层已经封装好了，你只要确认输入输出是对的就行，小细节上的超参数设定只会让训练的最终精度有所偏差，一般不会在一开始的时候就不收敛。你已经确认了模型结构没问题的话，如果学习率你已经尝试过不同的几个数量级都没有用，那是不是有可能是你的数据和对应标签有些问题？ArcFaceLoss只是用来给人脸识别项目锦上添花的，你可以试试不接这个层直接用Softmax输出的交叉熵作为损失函数训练几个Epoch试试，如果收敛那就是loss问题，如果没有那很可能是数据处理的时候出了一些问题。另外还有Margin Loss、Cosine Loss你也可以试试，接上不同的loss层对比效果等。不过以上都是我个人见解哈。
> 
> 好的，了解啦 ^_^，这么忙还打扰您，有些抱歉。非常非常感谢。

你好，此前我一直没时间review我的代码，最近查验了之后发现模型结构的细节实现上与原版有不少出入，我修改了一下。为了防止我误导你，跟你说一下哈。另外还有两件事：论文原版是将RGB格式的图片-127.5后除以128的，我是直接除以255.的，这里也有不同；数据增强的流程中我将crop到的人脸框再做resize，导致人脸的形状变化，这在人脸识别里不合理，所以数据增强的代码也需要修改。
