### ISSUE TITLE
Stride applied to first or second convolution of first bottleneck?

### ISSUE THREAD

**Issue by jolastar** [TMaysGGS/MobileFaceNet-Keras#3]
Hi, 

According to the [_MobileNetV2: Inverted Residuals and Linear Bottlenecks_](https://arxiv.org/pdf/1801.04381.pdf) paper, table 1 (below), the stride has to be applied to the second convolution (the depthwise convolution) of a bottleneck.

![image](https://user-images.githubusercontent.com/11660030/70136429-a8bab280-1694-11ea-8d7e-6538981247fa.png)

In your code (in the three occurrences) the stride is applied to the first convolution (the 1x1 convolution which performs the expansion), rather than in the second one.

I think this:

```python
    Z1 = conv_block(inputs, tchannel, 1, s, 'same')
    Z1 = DepthwiseConv2D(kernel, strides = 1, padding = "same", depth_multiplier = 1, use_bias = False)(Z1)
```

should become:

```python
    Z1 = conv_block(inputs, tchannel, 1, 1, 'same')
    Z1 = DepthwiseConv2D(kernel, strides = s, padding = "same", depth_multiplier = 1, use_bias = False)(Z1)
```

**Comment by TMaysGGS** [comment]
Hi @jolastar , 

I think you are right about this. Just checked the original paper and some others' works. Thank you for the check and I will correct it.

**Comment by jolastar** [comment]
Thank you for the correction in 237917bbbacde02b839788e36dd3dbcca15de3a9.

There is a third place where the same code needs to be fixed, for consistency:

https://github.com/TMaysGGS/MobileFaceNet-Keras/blob/237917bbbacde02b839788e36dd3dbcca15de3a9/MobileFaceNet_save_model_for_prediction.py#L45-L47

(It would make sense to have a single source file for the model architecture actually.)

**Comment by TMaysGGS** [comment]
> Thank you for the correction in [237917b](https://github.com/TMaysGGS/MobileFaceNet-Keras/commit/237917bbbacde02b839788e36dd3dbcca15de3a9).
> 
> There is a third place where the same code needs to be fixed, for consistency:
> 
> https://github.com/TMaysGGS/MobileFaceNet-Keras/blob/237917bbbacde02b839788e36dd3dbcca15de3a9/MobileFaceNet_save_model_for_prediction.py#L45-L47
> 
> (It would make sense to have a single source file for the model architecture actually.)

Hi @jolastar , 

Thank  you for your advice. This is like a workspace for me at the time I created it so it looks like that. I just packaged the model into a function in "Model_Structures" (rather than a class to keep it simple and clear to read).
